#服务器端口
server:
  port: 61016
  connection-timeout: 5000ms

#数据源配置
spring:
  application:
    name: w-service-like
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wa_yue?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
# mybatis #  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
mybatis-plus:
  mapper-locations: classpath*:com.me.likes.repository.mapper/*Mapper.xml

  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.me.likes.repository.entity

logging:
  level:
    com.me.likes.repository.mapper: DEBUG

  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      #是否开启大写命名，默认不开启
      #capital-mode: true
      #逻辑删除配置
      #logic-delete-value: 1
      #logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true